language:
  - go

sudo: false


go:
  - 1.9.x
  - 1.10.x
  - 1.11.x
  - 1.12.x
  - master

script:
  - go test -race -cover -covermode=atomic github.com/wanghuida/go-redis-ext/xredis/xhash

after_success:
  - bash <(curl -s https://codecov.io/bash)