language:
  - go

sudo: false

go:
  - 1.9.x
  - 1.10.x
  - 1.11.x
  - 1.12.x
  - master

script:
  - go test -v -coverprofile=coverage.txt -covermode=atomic ./xredis/xhash

after_success:
  - bash <(curl -s https://codecov.io/bash)